apiVersion: 1

datasources:
  - name: {{cookiecutter.library_name}}_data
    type: postgres
    url: {{cookiecutter.project_name}}-timescale-1:5431
    user: admin
    secureJsonData:
      password: 'Password!'
    jsonData:
      database: {{cookiecutter.library_name}}_data
      sslmode: 'disable' # disable/require/verify-ca/verify-full
      maxOpenConns: 100 # Grafana v5.4+
      maxIdleConns: 100 # Grafana v5.4+
      maxIdleConnsAuto: true # Grafana v9.5.1+
      connMaxLifetime: 14400 # Grafana v5.4+
      postgresVersion: 1500
      timescaledb: true