version: '3.8'

networks:
  {{cookiecutter.library_name}}-iotml-network:

volumes:
  timescale-data:
  grafana-data:
  nodered-data:
  nodered-node_modules:

services:

  preprocessing:
    build:
      context: ./src
      dockerfile: preprocessor_dockerfile
    restart: unless-stopped
    networks:
      - {{cookiecutter.library_name}}-iotml-network

  nodered:
    build:
      context: ./src
      dockerfile: nodered_dockerfile
    restart: unless-stopped
    mem_limit: 9G
    depends_on:
      - "timescale"
    logging:
      options:
        max-size: 10m
    networks:
      - {{cookiecutter.library_name}}-iotml-network
    expose:
      - 1880
    ports:
      - "1882:1880"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - nodered-data:/data/
      - nodered-node_modules:/cache/node_modules

    environment:
      - NODE_OPTIONS=--max_old_space_size=8192
      - POSTGRESS_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - FLOWS=example_ml_inference.json

  timescale:
    image: timescale/timescaledb-ha:pg15-all
    restart: unless-stopped
    mem_limit: 4G
    shm_size: 1G
    logging:
      options:
        max-size: 10m
    networks:
      - {{cookiecutter.library_name}}-iotml-network
    expose:
      - 5432
    ports:
      - '5431:5432'
    volumes:
      - timescale-data:/home/postgres/pgdata/data
      #- ./timescale/csvs:/csvs
      - ./src/sql:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=admin
      - POSTGRES_DB={{cookiecutter.library_name}}_data
    command:
      # https://wiki.postgresql.org/wiki/Tuning_Your_PostgreSQL_Server
      - -c
      - shared_buffers=1GB
      - -c
      - work_mem=32MB

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    mem_limit: 2G
    logging:
      options:
        max-size: 10m
    networks:
      - {{cookiecutter.library_name}}-iotml-network
    expose:
      - 3000
    ports:
      - "3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./src/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./src/grafana/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=1s
      #- GF_SMTP_ENABLED=${GF_SMTP_ENABLED}
      #- GF_SMTP_HOST=${GF_SMTP_HOST}
      - GF_INSTALL_PLUGINS=${GF_INSTALL_PLUGINS}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
