site_name: {{ cookiecutter.project_name | replace("_", " ") | title }}
theme: material
plugins:
  - include-markdown
  - search
  - include_dir_to_nav
  - mkapi
nav:
  - .
  - API Reference:
    - $api:src/{{ cookiecutter.project_name }}.***
