{
 "title": "Example Dashboard",
 "time": { "from": "2023-07-17T01:18:07.037Z", "to": "2023-07-23T01:06:48.534Z" },
 "templating": {
  "list": [
   {
    "name": "aggregation",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Time Series Data",
   "type": "timeseries",
   "description": "The Panel displays the value of some IoT device, along with the state at which the device is suppose to run (0 or 1)",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select \ntime_bucket('$aggregation', time) AS \"time\",\nAVG(y) AS \"y\",\nMAX(state) AS \"state\"\nFROM example_data WHERE $__timeFilter(\"time\") \nGROUP BY 1; "
    }
   ]
  },
  {
   "title": "Auto Encoder Squared Error",
   "type": "timeseries",
   "description": "Monitoring the error between the original time series and the time series reconstructed by the model",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT \n  time_bucket('$aggregation',time) AS \"time\",\n  AVG((model_output->>'squared_error')::double precision) AS \"inference_error\"\n\nfrom ai_model\n\nWHERE $__timeFilter(\"time\")\nGROUP BY 1 "
    }
   ]
  },
  {
   "title": "Latent Space Visualization",
   "type": "xychart",
   "description": "This plot show the 2D projection of each data point",
   "gridPos": { "h": 16, "w": 11, "x": 12, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT \n  time,\n  (replace(replace(model_output->>'pca_components','[','{'), ']','}')::double precision[][])[1][1] AS \"pca_x\",\n  (replace(replace(model_output->>'pca_components','[','{'), ']','}')::double precision[][])[1][2] AS \"pca_y\"\n\nFROM ai_model\nWHERE\n\n  (time BETWEEN '2023-05-29T00:00:00+02'::timestamp with time zone AND '2023-06-15T23:59:00+02'::timestamp with time zone);"
    },
    {
     "rawSql": "SELECT \n  time,\n  (replace(replace(model_output->>'pca_components','[','{'), ']','}')::double precision[][])[1][1] AS \"pca_x2\",\n  (replace(replace(model_output->>'pca_components','[','{'), ']','}')::double precision[][])[1][2] AS \"pca_y2\"\n\nFROM ai_model\nWHERE\n  time BETWEEN '2023-06-24 00:00:00+02'::timestamp with time zone AND '2023-06-25 23:00:00+02'::timestamp with time zone\n;"
    }
   ]
  }
 ]
}